name = "Sophia"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e3e490a3f0b31fe8e8cb2eea07e2f1354c155a8685f71f758a21cec88f7e054"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
