name = "Sophia"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b3e9119f6c4011e1ced06def3c5a508dd1f9ffd0bd75b660cf79b2ff51e9e10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
